# Generated by Django 4.1.3 on 2022-12-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0003_band_still_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
