# Generated by Django 4.1.3 on 2022-12-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0005_alter_band_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.IntegerField(choices=[(-1, 'not defined'), (0, 'rock'), (1, 'metal'), (2, 'pop'), (3, 'hip-hop'), (4, 'electronic'), (5, 'reggae'), (6, 'other')], default=-1),
        ),
    ]
