# Generated by Django 4.1.3 on 2022-12-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0010_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exercises_app.band'),
            preserve_default=False,
        ),
    ]
