# Generated by Django 4.1.3 on 2022-12-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0012_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='exercises_app.category'),
        ),
    ]
